### PR TITLE
Elite theme update

### PR DESCRIPTION
**Pull request by AllanOcelot**
Some small styling changes to the Elite theme update.

### CODE REVIEW

**Comment by Shillos** [comment]
This is a very nice theme, only the /list looks not so bad, but it's readable. can you see the dark theme on /list it looks a little off can't see the writting on the topics looks too dimm just a little css to darken it! Whenever you can! :-)

https://imgur.com/a/xvrJVYY

**Comment by AllanOcelot** [comment]
HI @Shillos  - this is a quick one to fix, I'll get it done now, thanks for letting me know :)!

**Comment by Shillos** [comment]
There is some more parts that are a bit grayed out in themes Dark and Nightswatch in kiwi settings general themes and message layout dropdowns they look gray.

https://imgur.com/a/JYK6RJJ

**Comment by AllanOcelot** [comment]
@Shillos - Only just seen your reply, I'll quickly get these tested in all themes and fixed :)

**Pull request merged**
