### PR TITLE
Default theme overhaul

### PR DESCRIPTION
**Pull request by AllanOcelot**
It's been a long time since we've looked at the actual 'structure' of the core kiwi theme files, and they have all gotten a bit messy.  I've spent time looking over the file, removing duplicates, sorting the styling into simple 'sections' etc. I've added a simple 'Information' section at the top of the file too.

@ItsOnlyBinary  yes, I will lint this file after review from yourself and @prawnsalad :P 
( I just didn't want to spend too much time if the work got rejected )

### CODE REVIEW

**Comment by AllanOcelot** [comment]
Ok so @ItsOnlyBinary  - I'm in the process of linting and implementing your suggestions but this linting has taken it's toll (It's literally the worst ahaha).

 Hoping to complete this all tomorrow so if you'd be willing to review again I'd appreciate it :)

**Comment by prawnsalad** [comment]
Since you're tidying these up, we could go all in and start using CSS vars to make basic themes a *lot* easier. That way we could have a standard theme .css that sets all the colouring using vars (eg. `color: var(--base-colour);`) then a theme file that sets all the vars up to their values eg. `--base-color: #121212;`. Creating a new colour theme would then just be changing the var values at the top of the file.

It was mentioned on IRC a while ago but halted due to IE11 lacking support, but it can be pollyfilled in Kiwi for full support.

**Comment by prawnsalad** [comment]
Default theme differences with master: https://imgur.com/b6MxP72
Also when in mobile view, clicking the close header of the sidebar highlights it red, waits a few seconds, and then decides to close.

**Comment by prawnsalad** [comment]
`--comp-bg-aboutbuffer-h4` should be a bit more descriptive for what it actually is, a header. How about `--comp-bg-aboutbuffer-header`

**Comment by prawnsalad** [comment]
* --comp-bg-networkname--active should be... --comp-bg-statebrowser-networkname ?
* message action text / traffic / etc should not be a brand colour
* links should be coloured too (used for channel links)
* invalid value line 1083, border-color: var(brand-bg-default);
* needs a statebrowser fg var? currently uses --brand-bg-default which is confusing when modifying the main background
* transitions should not be "all" - should be more specific
* selfuser border should be using --comp-border

**Comment by AllanOcelot** [comment]
- Active channel in the statebrowser's colour is white

**Comment by prawnsalad** [comment]
## Coffee theme
Network header background is missing. Configure network text colour looking weird
image

Should the away-status indicator be so luminous?
image


## Osprey
The channel info sidebar headers are still green
image

**Comment by AllanOcelot** [comment]
ADDED: new theme ELITE , for our Elite Dangerous communities out there, Preview ( https://imgur.com/a/vhSfekR)

**Pull request merged**
