### PR TITLE
Add setting nicklistSortByState

### LINKED ISSUE #434: Option to order the nicklist with away users last

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
closes #434

### CODE REVIEW

**Comment by ItsOnlyBinary** [comment]
prawn let me know if you like the theme additions, if so i can add them to the other themes ;)

**Comment by prawnsalad** [comment]
I would have expected this to display all away nicks at the top, but it actually sorts by prefix first, and then away status. Do we know what the norm is here for other clients?

**Comment by ItsOnlyBinary** [comment]
Not sure on norm for other clients but, It would not make sense to have away users at the top as we are not interested in away users only in active users. also its customary to have users with chan status' at the top

**Comment by ItsOnlyBinary** [comment]
rebased

**Comment by prawnsalad** [comment]
This looks OK now I'm looking at it though I'm not so sure about the `nicklistSortByState` name. Not entirely sure but maybe something like `nicklistOrderedAway`?

**Comment by ItsOnlyBinary** [comment]
nicklistGroupAway  ?

**Comment by prawnsalad** [comment]
That works. Also to default to `false` so we don't suddenly change everyones nicklist that they're used to.

**Comment by westor7** [comment]
I personally think `nicklistSortByState` is more clear here.

**Pull request merged**
