### PR TITLE
Fix: #218 - Notice messages now have styling on all themes.

### PR DESCRIPTION
**Pull request by AllanOcelot**
All themes now have styling for 'notice' messages in the messageList.

### CODE REVIEW

**Comment by prawnsalad** [comment]
All of these `.kiwi-messagelist-message.kiwi-messagelist-message-notice` selectors should just be `.kiwi-messagelist-message-notice`

**Comment by prawnsalad** [comment]
Do we not think this notice message styling is way out of line in comparison to the rest of kiwi?

image

**Comment by prawnsalad** [comment]
Not sure if you have finished with this PR yet, but that notice colour is still really weird looking...

**Comment by AllanOcelot** [comment]
Sorry @prawnsalad  - I thought I'd updated this PR on Friday with screenshots with some screenshots - I've recreated the screenshots + update below.

Currently we use a red colour for the notices, but maybe that's why it looks so bad? Red is meant to be used as a warning / issue type colour - so I've created the following mock ups of different colours on the default theme to get your feedback.

I've included some red colours to choose from aswell, incase red is a set standard for IRC client notice message etc. :) 

1. 
image

2. 
image

3.
image

4.
image

5.
image

6.
image


--- REDS
1.
image

2.
image


3.
image

**Comment by AllanOcelot** [comment]
Currently discussing reworking the way to we display notice and other prominent message types.

**Comment by AllanOcelot** [comment]
Closing in favour of our new PR : #935

**Pull request closed without merging**
