### PR TITLE
FIX: Settings and Close StateBrowser icon for mobile devices

### PR DESCRIPTION
**Pull request by AllanOcelot**
- Remove span from close
- Close icon in statebrowser is now absolute positioned
- Close icon same height as containerHeader height
- Settings icon clickable

### CODE REVIEW

**Comment by ItsOnlyBinary** [comment]
I think fa-chevron-left might be better for this, as its not really closing its just collapsing away

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary  & @prawnsalad  

Spent some time on this today - I've redone the appSettings, sidebar and stateBrowser close to try and make everything more consistent.

There is one bug I've come across so far - if you pin the userNick list, then the spacing for the filter goes off. This could easily be solved if we add a class to the sidebar if it's pinned - then I can edit the style based on that.

( Please test using the default theme, as thats the only one the colours have been done for :) )

**Comment by prawnsalad** [comment]
There is the `kiwi-container--sidebar-pinned` class added to the container once it's pinned. So you would use `.kiwi-container--sidebar-pinned .kiwi-sidebar { }`

**Comment by AllanOcelot** [comment]
Awesome - I'll make a fix now :)

**Comment by AllanOcelot** [comment]
@prawnsalad  @ItsOnlyBinary  - it would be good to get your feedback on this PR when you get some time :)

**Comment by AllanOcelot** [comment]
This PR is now outdated, the above items have been addressed by multiple new PR's since this was opened.

**Pull request closed without merging**
