### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by prawnsalad**
Enjoy!

### CODE REVIEW

**Comment by Shillos** [comment]
Sorry to bother you guys, but we are having issues with the other translator guy. I keep translating it to Greek and he is translating it back to English for no reason on certain parts, but for other he did well, where I have voted for his corrections. The issue is that either he doesn't care looking at the commnets section or he is totally ignoring the fact of my messages. For example Take op from, admin, halfop, voice, devoice, owner, although these are commands but many newbies may like them in Greek and not using English words but Greek. Dimitris Psirrakis (westor) must use Greek if we are going to translate things right for the project, but not for our own way, by using the Greek Dictionary if needed (recommended), without having issues on the translations. We are not co-operating if he doesn't comment chat with me in Crowdin. I had many mistakes and thankfully he did fix them and vise versa I did too for him. But the issue on those still remain unsolved!

**Comment by westor7** [comment]
You don't know how to translate from English to Greek and your old already translations were garbage, and you see that i translate all of them like the way i chose because i had a reason, and you revert my changes to add your shits that doesn't make any sense to anything, so don't change my translations and leave them as i have it, i have translate in my life more than 10 programs and i know better the IRC and what to write better than you cause i use it since you was neither even borned.

**Comment by Shillos** [comment]
It's not how you know better, it's for you to keep it as it should be and start being more kind with people on a service, not with that attitude friend. You are not better than me nor do I say I'm better, so focus on REAL Translations into Greek and NOT back to English. I don't care how many programs you translated for, just do what's right or leave the translation to someone that has a better atidute than you. I know also IRC for the past 20+ years I have my own irc little network I don't need to be told by anyone. You should talk to me on Comments on Crowdin not here and lets get to an agreement on things without having to argue on words here. My native language is Greek and I live in Cyprus has nothing to do with what you are saying. I made some mistakes like YOU also made mistakes, so you are not perfect either. So STOP being such with a bad aditute with me or anyuone that translates, cos translations are free for all and you are not to dectate over mine either friend! So Keep FOCUS on translations Please. Kindly I ask you to do this and next time talk to people in a kind way and answer on the Crodin Comments. You have do decide where you did the mistake where it says Take voice you can't use it with english but in Greek many users do not know the things we know on irc so keep translations to Greek. Don't make this your own translation as you are showing off now, it's not how you know things it's what you should be doing for this project not for your own goals. Get this straight in your head and stop this aditute you don't have the right to speak to me this way, just because I did some mistakes too as you did also, so lets get down to business and leave this childish way of yours behind! I apologise for my mistakes, but we need to make this work either way, not your way the projects way only!

**Comment by westor7** [comment]
I bet 1 thousand euros that this is your first time that you are translating items on crowdin, you had 1 ton of spell mistakes and i fixed them all then you revert my changes and replied me silly comments who is kid me? ok go play with barbies and stop fucking up that project because there are some companies that really want a serious Greek translations, i have translated Google Chrome (50% of hole project) in the past go look the translations there are already there, so stop bulling on crowdin by posting these NON-SENSE comments and leave my translations there, if you want more discussion about items visit the live IRC Support channel on Freenode (#Kiwiirc) and talk more there, i see no future between us but i can give a last try with you.

**Comment by Shillos** [comment]
That's what I was saying all along and i did leave messages on crowdin and never got answers back to get things going here with the project translation that's all i care not about the bad attitude and why i did mistakes, it should be about KiwiIRC not about what us and what and how many translations we did. We all make mistakes and I'm not perfect no were near! :) I told westor to stop insulting me I would rather give him a chance for this project. You guys made a lot of hard work and i don't condone in bad attitudes and insults it's bad already in the world... let's make a world of KiwiIRC, a better pleace to be! (sounded like a rhyme?) :) I love that idea @prawnsalad thank you for your understanding!

**Pull request merged**
