### PR TITLE
Create Znc.vue

### PR DESCRIPTION
**Pull request by TheMythPT**
I've tweaked this one to allow the to use only two fiels to connect to znc.
now its "username/network"  + ":" + "password"
Check it out and tell me what you think.

### CODE REVIEW

**Comment by TheMythPT** [comment]
Also, hopefully, the label where usually is only Username will be Username/Network.
Point me the errors if any.
If you like it, merge it! xD

**Comment by TheMythPT** [comment]
DO NOT MERGE.  i can't get it to work on my test machine

**Comment by TheMythPT** [comment]
Able to be merged.

**Comment by prawnsalad** [comment]
I'm going to close this PR as the other ZNC startup screen PR was more complete and tied into the new startup screen style.

**Pull request closed without merging**
