### PR TITLE
Fix selected colour not remaining after sending a message

### LINKED ISSUE #130: Text color temporarily resets to black when text entry field loses focus
Text color is temporarily reset after an empty text input loses focus. 

Steps to reproduce:
1. Set text color.
2. Send something. Note that the text is the color you selected.
3. Click out of the text input, change channels, or something else to lose text area focus.
4. Click back in, send something. Note that the text is black again.
5. Send another thing without losing focus on text entry. Note that text is the color you selected again.

### LINKED ISSUE #592: Text colors being reset when sending the message
When we choose a text color, after hitting Enter to send the message, the color is reset.

I'm facing this issue in Chrome for Linux and Chrome for Android. 

Cheers.

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
fixes #592
fixes #130

### CODE REVIEW

**Comment by ItsOnlyBinary** [comment]
Also includes fixes for....
Applying colour after removing placeholder (empty input box)
fixes #291 Colored Font makes it so that Commands are sent as channel message

**Comment by utoxin** [comment]
Is there a reason this hasn't been approved yet? My users are all experiencing this, and it would be nice to have a fix.

**Comment by ItsOnlyBinary** [comment]
This fix requires some more research, as there maybe a better fix

**Comment by TheBeerbarian** [comment]
I like the bug that the color is reset to default after sending a message.  If it is fixed I would like the current bug to be a feature that can be a configured option.
With self hosted platforms used for my IRCd, I rather discourage people from constantly talking in color and rather it reset after a message.
Thanks. :)

**Pull request merged**
