### PR TITLE
EXPERIMENTAL: Giphy integration 

### PR DESCRIPTION
**Pull request by AllanOcelot**
Adding in Giphy to Kiwi will give us the same level of functionality that many of our users have come to expect from Kiwi.

This is an experimental build, currently it is unstyled and there are plenty of bugs whilst we try to decide on the best method for inserting the gifs into the messageList component. I belive we are parsing for HTML tags in messages, and as such, it is removing the gifs when a user submits their gif.

### CODE REVIEW

**Comment by AllanOcelot** [comment]
Update:

So , we need to add in some kind of sniffing for .gif image links, that will display the gif inline in Kiwi.

I am however, aware our users are pretty split, so I would not want to display gifs unless the end user wants them displayed. We could do this with another user option: 'Enable inline image's' or something similar. I can provide and wire up the option but I am out of my depth when it comes to displaying the images inline in the messageList.

Anyone who feels they can help out, please feel free to point me in the right direction ❤️

**Comment by Shillos** [comment]
Would be nice to see this feature in soon!

**Comment by AllanOcelot** [comment]
Hi @Shillos  -  we are still working on it, hopefully the bugs will be ironed out soon :)

**Comment by Shillos** [comment]
Very much looking forward to this! Thanks!

**Comment by Shillos** [comment]
Any luck with this one?!

**Comment by AllanOcelot** [comment]
@Shillos  - Our very own @ItsOnlyBinary  managed to take my code and made a working plugin that can added to your Kiwi install.  ( https://github.com/ItsOnlyBinary/my-kiwiirc-plugins ).

**Comment by Shillos** [comment]
Oh that's great! I was wondering if this could be released as a plugin. Thanks!

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary  has created a fully featured plugin that achieves this. There's no need for this PR anymore.

**Pull request closed without merging**
