### PR TITLE
Fix auto complete replacing words when no replacement is selected

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
to reproduce this issue start typing something that will not complete to a nick, press tab (invisibility opens an empty auto complete list) then press space. The text you started typing will be replace by emptiness

also typing a none auto completing word press tab then try continue typing

### CODE REVIEW

**Comment by 790** [comment]
There's a small visual distortion as the autocomplete still appears, but empty. Another way to fix might be to check filteredItems and have the autocomplete close itself on mount if there's nothing to display.

**Comment by ItsOnlyBinary** [comment]
that is somewhat intentional, as its desired that on backspace auto complete would start showing options (when triggered with #/@), i will however look into closing auto complete when its triggered by tab if there is no results (if thats possible)

**Comment by ItsOnlyBinary** [comment]
AutoComplete.vue could do with a tidy up, i will add that on sunday

**Comment by ItsOnlyBinary** [comment]
empty auto complete can become populated when a user start to remove chars.

closed in favour of #1479

**Pull request closed without merging**
