### PR TITLE
polyfill's for vue-virtual-scroller & ie11

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**

### CODE REVIEW

**Comment by 790** [comment]
vue-virtual-scroller in IE11 also requires the `'core-js/fn/array/virtual/includes'` polyfill.

**Comment by ItsOnlyBinary** [comment]
are you sure its not String.includes? thats what got dev server working in ie11 but didnt seem related to virtual scroller

**Comment by 790** [comment]
`validator: (value) => ['vertical', 'horizontal'].includes(value)`

Is the code from vue-virtual-scroller that was throwing the error. Happened when trying to /join a new channel from the server buffer.

There's also an error in IE11 where we use `String.startsWith`. There's only 1 instance of this use so maybe not worth adding it to the polyfills and we can change it to use indexOf

**Comment by ItsOnlyBinary** [comment]
it was caching tricking me into thinking it was string.includes it would seem, i just noticed the startsWith issue myself, so have added a fix in this pr for it (will be pushing shortly)

**Pull request merged**
