### PR TITLE
Cyrrilic username allow

### PR DESCRIPTION
**Pull request by wipedlifepotato**

### CODE REVIEW

**Comment by prawnsalad** [comment]
This won't be merged into the main project as it's not standard IRC. But you can put the regex in your config for your use case https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options#nick_format

**Comment by wipedlifepotato** [comment]
thx

**Comment by acetoneRu** [comment]
man, it don't works.
if I use `"nick_format": "[a-z_][a-z_0-9]"` I can input username only "[a-z_][a-z_0-9]". Regex don't works

**Comment by prawnsalad** [comment]
You would need to actually put the regex you need. ".+" for any character for example

**Comment by wipedlifepotato** [comment]
> You would need to actually put the regex you need. ".+" for any character for example

not work too.
And i cant create server to localhost:6668
```
lialh4@RBH4:~/toDelete/kiwiirc$ serve -s dist -l 5555 -d

   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:5555       │
   │   - On Your Network:  http://192.168.1.237:5555   │
   │                                                   │
   │   Copied local address to clipboard!              │
   │                                                   │
   └───────────────────────────────────────────────────┘

```
```
$ cat config.json 
{
    "windowTitle": "этозалупа",
    "startupScreen": "welcome",
    "kiwiServer": "",
    "restricted": true,
    "theme": "Elite",
    "themes": [
        { "name": "Default", "url": "static/themes/default" },
        { "name": "Dark", "url": "static/themes/dark" },
        { "name": "Coffee", "url": "static/themes/coffee" },
        { "name": "GrayFox", "url": "static/themes/grayfox" },
        { "name": "Nightswatch", "url": "static/themes/nightswatch" },
        { "name": "Osprey", "url": "static/themes/osprey" },
        { "name": "Radioactive", "url": "static/themes/radioactive" },
        { "name": "Sky", "url": "static/themes/sky" },
        { "name": "Elite", "url": "static/themes/elite" }
    ],
    "startupOptions" : {
        "channel": "#ru",
        "nick": "ЮзерБлять?",
	"server": "localhost",
	"port": 6668,
	"tls": false,
	"direct": false,
	"infoContent": "<p>Это залупа не работате нихуя</p>",
	"infoBackground":	"/",
	"autoConnect": true
    },
    "embedly": {
        "key": ""
    },
    "plugins": [
        { "name": "customise", "url": "static/plugins/customise.html" }
    ]
}
```

**Comment by prawnsalad** [comment]
I don't see it in your config file.

Add `"nick_format": ".+"` to the `startupOptions` section.

**Comment by wipedlifepotato** [comment]
> I don't see it in your config file.
> 
> Add `"nick_format": ".+"` to the `startupOptions` section.

<acetone> 11:28:01 AM - lialh4_: acetone, "You would need to actually put the regex you need. ".+" for any character for example"
<acetone> я эту залупу в самом начале пробовал
<acetone> написал в твоем же реквесте коммент

**Comment by acetoneRu** [comment]
`{
        "windowTitle": "ILITA IRC",
        "startupScreen": "welcome",
        "kiwiServer": "/webirc/kiwiirc/",
        "theme": "default",
        "restricted": "true",
        "hide_advanced": "true",
        "buffer.block_pms": "true",
        "themes": [
                { "name": "Default", "url": "static/themes/default" },
                { "name": "Dark", "url": "static/themes/dark" },
                { "name": "Coffee", "url": "static/themes/coffee" },
                { "name": "GrayFox", "url": "static/themes/grayfox" },
                { "name": "Nightswatch", "url": "static/themes/nightswatch" },
                { "name": "Osprey", "url": "static/themes/osprey" },
                { "name": "Radioactive", "url": "static/themes/radioactive" },
                { "name": "Sky", "url": "static/themes/sky" }
        ],
        "startupOptions" : {
                "channel": "#ru",
                "nick": "WebClient?",
                "greetingText": "ILITA",
                "nick_format": ".+",
                "infoBackground": "/background_freedom.jpg",
                "infoContent": "<p>irc.acetone.i2p:6667 (I2P)<br>[324:9de3:fea4:f6ac::41]:6667 (Yggdrasil)</p><p style=\"color: grey;\">#ru #en</p>"
        }
}`

**Comment by acetoneRu** [comment]
Any regex is not worked

**Comment by wipedlifepotato** [comment]
open source

**Comment by prawnsalad** [comment]
Sorry, I missed the complete regex. `"nick_format": "/.*/"`

**Comment by acetoneRu** [comment]
Many thanks for answer! Now it works, button working correctly. But... But Kiwi needed more configuration options. I have message: `Closing Link: аТыГоворишьОпенцурс[localhost] (Hostile username. Please use only 0-9 a-z A-Z _ - and . in your username.)`

**Pull request closed without merging**
