### PR TITLE
Create app.uk-UA.po

### PR DESCRIPTION
**Pull request by a-polivanchuk**
Create Ukrainian translation

### CODE REVIEW

**Comment by prawnsalad** [comment]
That is great :)

I've uploaded it to our translation manger at http://translations.kiwiirc.com/translate/kiwiirc/5/en-uk

If you sign up there and complete the 1 missing translation then I can merge it into the project.

Tip - Click the "Other Languages" tab to see what the translation is in English and other languages.

**Comment by a-polivanchuk** [comment]
Oh, that's great you have the localization project on Crowdin!
I couldn't find where the project is localized and created my own project on Crowdin too:)

So now I'm going to delete it.

The second commit with updated translations done.

**Comment by prawnsalad** [comment]
Any changes need to be made on the translation manager I linked to, not the .po file. I expert the final .po files from the website once it is complete.

**Comment by a-polivanchuk** [comment]
OK, now it's completed on translation manager

**Comment by prawnsalad** [comment]
Awesome! I've merged + updated it live: https://kiwiirc.com/nextclient/?language=uk-ua

Hopefully today I will have it automatically detecting your language from your browser settings, but that link will let you test it and make sure it's working as expected.

I'll close this PR now but anything else just drop a message here. Thanks!

**Pull request closed without merging**
