### PR TITLE
Stylelint more folders

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**

### CODE REVIEW

**Comment by prawnsalad** [comment]
Could you update this from master, then I can spend some time with @AllanOcelot going through the themes to get this merged

**Comment by ItsOnlyBinary** [comment]
rebased

**Comment by ItsOnlyBinary** [comment]
@AllanOcelot would be great if you could look through this to make sure i didnt break anything, especially with the radioactive theme as it had lots of duplicated parts etc, i generally opted for the second definition, or merged them if there was differences.

**Comment by prawnsalad** [comment]
`<itsonlybinary>	that can be closed it will need to be redone for new vue. we still are not linting themes`

**Pull request closed without merging**
