### PR TITLE
Added theme for usage in stream chat overlays

### PR DESCRIPTION
**Pull request by siltwood**
Added theme suitable for making Kiwi IRC act as a chat overlay component that can be used in OBS Studio or Streamlabs OBS

### CODE REVIEW

**Comment by ivarmlee11** [comment]
Before this gets merged I need to do some more minor changes...

**Comment by AllanOcelot** [comment]
@ivarmlee11 can you generate some screens shots of this in use for us? Will be easier to test than downloading a streaming client etc :)

**Comment by ivarmlee11** [comment]
I want to find an alternative to the text shadow effect I used to highlight darker usernames on the Kiwi chat window's opaque black window. I am also going to look into some padding and margin changes as well as look at a way to handle emotes.

**Comment by ivarmlee11** [comment]
@AllanOcelot yeah I'll show what it looks like currently

**Comment by ivarmlee11** [comment]
@AllanOcelot 
overlay
Here's one, throwing up some more after I fix an issue with max-width.

**Comment by ivarmlee11** [comment]
@AllanOcelot Here's one with a bit more spam 
overlay-2

**Comment by ivarmlee11** [comment]
Just spotted an issue when users with a charity relief icon prepended to their Twitch username send a message, their nick appears to be unstyled. Attempting to recreate this.

**Comment by AllanOcelot** [comment]
At a glance from those screenshots, it looks great @ivarmlee11  - it's something we have been wanting to add into Kiwi for a while, you've done a solid job of doing it.

I'll ask Prawn to review it when I see him in person tomorrow - hopefully we can get more of the streaming community using Kiwi. 

Maybe something to look into would be making a nodeJS bot, that connects to twitch's IRC and watches for donation/follow etc events - and then messages the channel?

**Comment by ivarmlee11** [comment]
> Maybe something to look into would be making a nodeJS bot, that connects to twitch's IRC and watches for donation/follow etc events - and then messages the channel?

For anyone curious, I am currently using TMI.js to achieve this.

**Comment by ivarmlee11** [comment]
Here's the bot so far for anyone curious -> https://hastebin.com/gevajezinu.js

**Pull request closed without merging**
